version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: groweasy-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: groweasy
    volumes:
      - mongodb_data:/data/db
    networks:
      - groweasy-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: groweasy-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/groweasy?authSource=admin
      - DATABASE_NAME=groweasy
      - SECRET_KEY=your-secret-key-change-this-in-production
      - DEBUG=True
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - groweasy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: groweasy-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - groweasy-network

volumes:
  mongodb_data:

networks:
  groweasy-network:
    driver: bridge 